spring.application.name=backend
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.ssl_mode=require

# Security
jwt.secret=${JWT_SECRET:manam_ktdm_secret_key_2024_must_be_256_bits_long_enough}
jwt.expiration=604800000

# Server port
server.port=${PORT:8080}
